### ISSUE TITLE
t-14-5-01.R and t-14-5-02.R: different behaviors when run in console vs. as a job

### ISSUE THREAD

**Issue by xiaohuagong** [atorus-research/CDISC_pilot_replication#3]
There R scripts run fine with a clean state console session.  However, when they are submitted as Local Jobs, errors encountered when the `ae_counts()` function fails to resolve one of its default parameters `N_counts` to the `header_n` object.

**Comment by atorus-research** [comment]
Thank you for this feedback! 

This issue seems to spawn from the `ae_counts` function having a parameter default to a specific object name of `header_n`. Interactively and  when the file is sourced, this ran fine - but run in a local job there's a conflict as the variable doesn't exist. Defaulting a function parameter to an assumed object reference is not best practice, so we have updated this function to require that the parameter `N_counts` is explicitly stated, and related table scripts have been updated.
